services:

    backend:
        build:
            dockerfile: Dockerfile
        volumes:
            - static_value:/app/static/
            - media_value:/app/media/
        ports:
            - 8000:8000
        restart: always

volumes:
    static_value:
    media_value:
