# Generated by Django 5.1 on 2024-08-19 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=31, verbose_name='Город')),
                ('timezone', models.CharField(max_length=31, verbose_name='Часовой пояс')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=127, verbose_name='Уровень образования')),
                ('organization', models.CharField(max_length=127, verbose_name='Учебное заведение')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('additional', models.BooleanField(blank=True, null=True, verbose_name='Дополнительное образование')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Название интереса')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core', models.CharField(max_length=127, verbose_name='Основное навык')),
                ('language', models.CharField(max_length=127, verbose_name='Язык программирования')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=31, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=31, verbose_name='Фамилия')),
                ('login', models.CharField(max_length=127, verbose_name='Логин')),
                ('password', models.CharField(max_length=127, verbose_name='Пароль')),
                ('telephone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('telephone_work', models.CharField(max_length=15, verbose_name='Рабочий телефон')),
                ('default_telephone', models.BooleanField(default=True, verbose_name='Телефон по умолчанию')),
                ('telegram', models.CharField(max_length=127, verbose_name='Телеграм')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('start_schedule', models.TimeField(verbose_name='Начало рабочего времени')),
                ('end_schedule', models.TimeField(verbose_name='Конец рабочего времени')),
                ('dey_week', models.CharField(max_length=15, verbose_name='Рабочие дни недели')),
                ('start_absence', models.DateField(blank=True, null=True, verbose_name='Начало отсутствия')),
                ('end_absence', models.DateField(blank=True, null=True, verbose_name='Конец отсутствия')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images', verbose_name='Фото')),
                ('hobby', models.CharField(blank=True, max_length=127, null=True, verbose_name='Хобби')),
                ('success', models.CharField(blank=True, max_length=127, null=True, verbose_name='Успехи')),
                ('languages', models.CharField(max_length=127, verbose_name='Языки')),
                ('position', models.CharField(max_length=127, verbose_name='Должность')),
                ('department', models.CharField(blank=True, choices=[('Разработка', 'Разработка'), ('Архитектура', 'Архитектура'), ('ИБ', 'ИБ'), ('Аналитика', 'Аналитика'), ('Инфраструктура', 'Инфраструктура')], max_length=127, null=True, verbose_name='Отдел')),
                ('format_work', models.CharField(max_length=127, verbose_name='Формат работы')),
                ('availability', models.CharField(max_length=127, verbose_name='Доступность')),
                ('grade', models.CharField(max_length=127, verbose_name='Квалификация')),
                ('staff', models.BooleanField(default=True, verbose_name='Сотрудник отдела')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.address', verbose_name='Адрес')),
                ('deputy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputies', to='employee.employee', verbose_name='Заместитель')),
                ('education', models.ManyToManyField(blank=True, to='employee.education', verbose_name='Университет')),
                ('leadership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='employee.employee', verbose_name='Руководитель')),
            ],
        ),
    ]
