# Generated by Django 5.1 on 2024-08-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='specialization',
        ),
    ]
