# Generated by Django 5.1 on 2024-08-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='additional',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Дополнительное образование'),
        ),
    ]
