# Generated by Django 5.1 on 2024-08-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_specialization'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='teams_employee', to='team.team', verbose_name='Команды'),
        ),
    ]
