# Generated by Django 5.1 on 2024-08-15 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='employee.employee', verbose_name='Сотрудник, на которого показывается')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='employee.employee', verbose_name='Подписчик, который подписывается')),
            ],
        ),
    ]
