# Generated by Django 5.1 on 2024-08-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_teams'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='projects_employee', to='team.project', verbose_name='Проекты'),
        ),
    ]
