# Generated by Django 5.1 on 2024-08-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='education',
        ),
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.ManyToManyField(blank=True, to='employee.education', verbose_name='Университет'),
        ),
    ]
