# Generated by Django 5.1 on 2024-08-18 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание проекта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/projects', verbose_name='Изображение проекта')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('ended', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('archived', models.BooleanField(default=False, verbose_name='Архивировано')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaders_projects', to='employee.employee', verbose_name='Руководитель проекта')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название команды')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('ended', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('archived', models.BooleanField(default=False, verbose_name='Архивировано')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaders_teams', to='employee.employee', verbose_name='Руководитель команды')),
                ('projects', models.ManyToManyField(related_name='teams_projects', to='team.project', verbose_name='Проекты')),
            ],
        ),
    ]
